import DiagnosticConfidence from "@/components/diagnostics/DiagnosticConfidence";
import DiagnosticEvidence from "@/components/diagnostics/DiagnosticEvidence";

const categoryLabels = { allocation: "Alocação", diversification: "Diversificação", concentration: "Concentração", income: "Renda", risk: "Risco", data_quality: "Qualidade dos dados" };
const severityLabels = { high: "Severidade elevada", medium: "Severidade moderada", low: "Severidade baixa", info: "Informativo" };

export default function DiagnosticItem({ diagnostic }) {
  return <article className="rounded-2xl border border-white/[.07] bg-black/[.12] p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap gap-2"><span className="rounded-full border border-white/[.08] px-2.5 py-1 text-[10px] uppercase tracking-[.12em] text-[#8e948f]">{categoryLabels[diagnostic.category] || diagnostic.category}</span><span className="rounded-full border border-[#d9b86c]/20 bg-[#d9b86c]/[.05] px-2.5 py-1 text-[10px] uppercase tracking-[.12em] text-[#c9ad6a]">{severityLabels[diagnostic.severity] || diagnostic.severity}</span></div><h3 className="mt-3 text-sm font-semibold text-[#e7e7e2]">{diagnostic.title}</h3><p className="mt-2 text-xs leading-5 text-[#858b86]">{diagnostic.summary}</p></div><div className="shrink-0"><DiagnosticConfidence value={diagnostic.confidence} /></div></div><details className="group mt-4 border-t border-white/[.06] pt-3"><summary className="cursor-pointer rounded-lg text-xs font-semibold text-[#b6bbb6] outline-none transition hover:text-white focus-visible:ring-2 focus-visible:ring-[#d9b86c]/60 focus-visible:ring-offset-4 focus-visible:ring-offset-[#101311]">Ver evidências e detalhes <span aria-hidden="true" className="ml-1 inline-block transition group-open:rotate-180">⌄</span></summary><div className="mt-4"><DiagnosticEvidence evidence={diagnostic.evidence} metrics={diagnostic.metrics} limitations={diagnostic.limitations} /></div></details></article>;
}
