import { Activity, AlertCircle, BarChart3 } from "lucide-react";
import Link from "next/link";
import DiagnosticItem from "@/components/diagnostics/DiagnosticItem";
import DiagnosticScoreCard from "@/components/diagnostics/DiagnosticScoreCard";

const scores = [["diversification", "Diversificação", "sector-diversification"], ["concentration", "Concentração", "top-three-concentration"], ["income_resilience", "Resiliência de renda", "income-concentration"], ["data_quality", "Qualidade dos dados", "missing-metadata"]];
const severity = { high: 4, medium: 3, low: 2, info: 1 }, status = { attention: 3, observed: 2, insufficient_data: 1, not_applicable: 0 };

export default function PortfolioDiagnosticsPanel({ result, error, loaded, positionsCount, strategyConfigured }) {
  if (!loaded) return <State icon={Activity} title="Calculando diagnóstico" text="Organizando os fatos disponíveis da carteira." />;
  if (error) return <State icon={AlertCircle} title="Diagnóstico indisponível" text={error} />;
  if (!positionsCount) return <State icon={BarChart3} title="Diagnóstico da carteira" text="Registre uma posição para gerar diagnósticos patrimoniais." />;
  if (!result) return <State icon={AlertCircle} title="Dados insuficientes" text="Ainda não há dados estruturados suficientes para apresentar o diagnóstico." />;
  const general = result.diagnostics.filter((item) => !item.scope), strategic = prioritize(result.diagnostics.filter((item) => item.scope === "strategy" && item.status === "attention")).slice(0, 3), coherence = prioritize(result.diagnostics.filter((item) => item.scope === "risk_profile" && item.status === "attention")).slice(0, 3), behavior = prioritize(result.diagnostics.filter((item) => item.scope === "behavior")).slice(0, 4);
  return <section className="mt-6" aria-labelledby="portfolio-diagnostics-title">
    <div className="mb-4 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Leitura patrimonial</p><h2 id="portfolio-diagnostics-title" className="font-display mt-2 text-2xl">Diagnóstico da carteira</h2></div><p className="max-w-lg text-xs leading-5 text-[#737973]">Pontuações descritivas. Não representam qualidade absoluta nem orientação financeira.</p></div>
    <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">{scores.map(([key, title, id]) => <DiagnosticScoreCard key={key} title={title} score={result.scores[key]} summary={general.find((item) => item.id === id)?.summary || "Sem resumo disponível."} />)}</div>
    <DiagnosticGroup title="Diagnóstico geral" description="Até cinco fatos baseados nas regras padrão." items={prioritize(general).slice(0, 5)} empty="A engine não retornou diagnósticos gerais relevantes." />
    <DiagnosticGroup title="Diagnóstico da sua estratégia" description="Até três divergências baseadas nas referências definidas por você." items={strategic} empty={strategyConfigured ? "Nenhuma divergência estratégica foi identificada." : "Defina sua estratégia para personalizar os diagnósticos."} badge={strategyConfigured ? "Estratégia considerada" : null} link="/configuracoes#estrategia-carteira" linkText={strategyConfigured ? "Editar preferências" : "Definir estratégia"} />
    <DiagnosticGroup title="Coerência com seu perfil" description="Até três divergências contextualizadas pelas respostas do questionário." items={coherence} empty={result.context?.riskProfileConfigured ? "Nenhuma divergência de coerência foi identificada." : "Defina seu perfil para contextualizar a análise."} badge={result.context?.riskProfileConfigured ? `Perfil ${profileLabel(result.context.calculatedProfile)}` : null} link="/configuracoes#perfil-risco" linkText={result.context?.riskProfileConfigured ? "Editar perfil" : "Definir perfil"} />
    <div className="card mt-4 rounded-2xl p-4 sm:p-6"><div className="mb-4"><p className="eyebrow">Histórico de operações</p><h3 className="font-display mt-2 text-xl">Padrões de comportamento</h3><p className="mt-1 text-xs text-[#737973]">Fatos observados nos registros, sem inferência de intenção.</p></div><div className="mb-4 max-w-sm"><DiagnosticScoreCard title="Consistência comportamental" score={result.scores.behavior_consistency} summary="Regularidade, estabilidade do ritmo, dispersão dos aportes e suficiência do histórico." /></div>{behavior.length ? <div className="space-y-3">{behavior.map((item) => <DiagnosticItem key={item.id} diagnostic={item} />)}</div> : <p className="rounded-xl border border-white/[.06] p-5 text-sm text-[#858b86]">{result.context?.behaviorHistorySufficient ? "Nenhum padrão relevante foi identificado." : "Histórico insuficiente. Continue registrando operações para observar padrões ao longo do tempo."}</p>}</div>
  </section>;
}

function DiagnosticGroup({ title, description, items, empty, badge, link, linkText }) { return <div className="card mt-4 rounded-2xl p-4 sm:p-6"><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-display text-xl">{title}</h3>{badge && <span className="rounded-full border border-[#d9b86c]/25 px-2.5 py-1 text-[10px] uppercase tracking-[.12em] text-[#d9b86c]">{badge}</span>}</div><p className="mt-1 text-xs text-[#737973]">{description}</p></div>{link && <Link href={link} className="rounded-lg px-3 py-2 text-xs font-semibold text-[#d9b86c] outline-none focus-visible:ring-2 focus-visible:ring-[#d9b86c]/60">{linkText}</Link>}</div>{items.length ? <div className="space-y-3">{items.map((item) => <DiagnosticItem key={item.id} diagnostic={item} />)}</div> : <p className="rounded-xl border border-white/[.06] p-5 text-sm text-[#858b86]">{empty}</p>}</div>; }
function State({ icon: Icon, title, text }) { return <section className="card mt-6 rounded-2xl p-6" aria-live="polite"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#d9b86c]/[.08] text-[#d9b86c]"><Icon size={18} /></span><div><h2 className="font-display text-xl">{title}</h2><p className="mt-2 text-xs text-[#777d78]">{text}</p></div></div></section>; }
function prioritize(items = []) { return items.map((item, index) => ({ item, index })).sort((a, b) => (severity[b.item.severity] || 0) - (severity[a.item.severity] || 0) || (status[b.item.status] || 0) - (status[a.item.status] || 0) || Number(b.item.confidence || 0) - Number(a.item.confidence || 0) || a.index - b.index).map(({ item }) => item); }
function profileLabel(value) { return ({ conservative: "conservador", moderate: "moderado", aggressive: "agressivo" })[value] || "calculado"; }
