"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import KnowledgeSearch from "@/components/knowledge/KnowledgeSearch";
import KnowledgeSidebar from "@/components/knowledge/KnowledgeSidebar";
import KnowledgeArticle from "@/components/knowledge/KnowledgeArticle";
import { getArticlesByCategory, getCategoryHref, getKnowledgeCategories, searchArticles } from "@/lib/knowledge/knowledgeService";
import { brandConfig } from "@/lib/config/brandConfig";
export default function KnowledgeHome() { const [query, setQuery] = useState(""); const results = useMemo(() => query.trim() ? searchArticles(query).slice(0, 12) : [], [query]); const categories = getKnowledgeCategories(); return <div className="page-container"><header className="max-w-3xl"><p className="eyebrow">Documentação oficial</p><h1 className="font-display mt-2 text-3xl sm:text-4xl">Central de Conhecimento</h1><p className="mt-3 text-sm leading-6 text-[#777d78]">Aprenda funcionalidades, conceitos e indicadores do {brandConfig.appName} em conteúdo estruturado e versionado.</p></header><div className="mt-8"><KnowledgeSearch value={query} onChange={setQuery} /></div><div className="mt-6 grid gap-5 lg:grid-cols-[15rem_minmax(0,1fr)]"><KnowledgeSidebar /><main className="min-w-0">{query ? <div><p className="mb-4 text-xs text-[#777d78]">{results.length} resultado(s) para “{query}”</p><div className="space-y-4">{results.map((item) => <KnowledgeArticle key={item.id} article={item} />)}{!results.length && <div className="card rounded-2xl p-8 text-center text-sm text-[#777d78]">Nenhum conteúdo encontrado.</div>}</div></div> : <div className="grid gap-3 sm:grid-cols-2">{categories.map(({ id, label }) => <Link key={id} href={getCategoryHref(id)} className="card rounded-2xl p-5 transition hover:border-[#d9b86c]/25"><p className="font-display text-xl">{label}</p><p className="mt-2 text-xs text-[#777d78]">{getArticlesByCategory(id).length} artigo(s)</p></Link>)}</div>}</main></div></div>; }
