"use client";

import Link from "next/link";
import { ArrowDownRight, ArrowUpRight, BriefcaseBusiness, Coins, Plus, WalletCards } from "lucide-react";
import PositionsTable from "@/components/portfolio/PositionsTable";
import useInvestmentData from "@/hooks/useInvestmentData";
import { currency, percent } from "@/lib/engine/totals";

function MetricCard({ label, value, detail, icon: Icon, tone = "neutral", featured = false }) { return <article className={`card rounded-2xl p-5 ${featured ? "md:col-span-2 md:p-7" : ""}`}><div className="flex items-start justify-between gap-4"><div className="min-w-0"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#777d78]">{label}</p><p className={`${featured ? "mt-4 text-3xl sm:text-4xl" : "mt-3 text-2xl"} break-words font-semibold tracking-tight [overflow-wrap:anywhere] ${featured ? "gold-text" : ""}`}>{value}</p>{detail && <p className={`mt-2 flex items-center gap-1 text-xs ${tone === "positive" ? "text-emerald-400" : tone === "negative" ? "text-rose-400" : "text-[#777d78]"}`}>{tone === "positive" ? <ArrowUpRight size={14} /> : tone === "negative" ? <ArrowDownRight size={14} /> : null}{detail}</p>}</div><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${featured ? "bg-[#d9b86c] text-[#090b0a]" : "border border-white/8 text-[#d9b86c]"}`}><Icon size={19} /></span></div></article>; }

export default function Dashboard() {
  const { operations, positions, totals, loaded, storageError } = useInvestmentData();
  const tone = totals.profit > 0 ? "positive" : totals.profit < 0 ? "negative" : "neutral";
  return <div className="page-container"><header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Painel financeiro</p><h1 className="font-display mt-2 text-3xl sm:text-4xl">Sua carteira, <span className="italic text-[#8b908b]">sob controle.</span></h1><p className="mt-3 max-w-lg text-sm text-[#777d78]">Patrimônio calculado a partir de {operations.length} {operations.length === 1 ? "operação" : "operações"}.</p></div><Link href="/operacoes" className="gold-button flex items-center justify-center gap-2"><Plus size={16} />Nova operação</Link></header><section className="mt-8 grid gap-3 sm:grid-cols-2 md:grid-cols-4"><MetricCard featured label="Patrimônio total" value={currency.format(totals.current)} detail={`${positions.length} ${positions.length === 1 ? "ativo" : "ativos"} na carteira`} icon={BriefcaseBusiness} /><MetricCard label="Valor investido" value={currency.format(totals.invested)} icon={WalletCards} /><MetricCard label="Lucro / prejuízo" value={currency.format(totals.profit)} detail={`${totals.profit >= 0 ? "+" : ""}${percent.format(totals.profitability)}% sobre o investido`} tone={tone} icon={totals.profit >= 0 ? ArrowUpRight : ArrowDownRight} /><MetricCard label="Rentabilidade total" value={`${totals.profitability >= 0 ? "+" : ""}${percent.format(totals.profitability)}%`} tone={tone} icon={ArrowUpRight} /><MetricCard label="Proventos recebidos" value={currency.format(totals.dividends)} detail="Total acumulado" icon={Coins} /></section><section className="card mt-8 overflow-hidden rounded-2xl"><div className="flex items-center justify-between border-b border-white/[.06] p-5 sm:p-6"><div><h2 className="font-display text-xl">Resumo da carteira</h2><p className="mt-1 text-xs text-[#777d78]">Consolidado das suas operações</p></div><Link href="/carteira" className="text-xs font-bold text-[#d9b86c]">Ver carteira</Link></div>{loaded ? <PositionsTable positions={positions.slice(0, 5)} /> : <div className="p-12 text-center text-sm text-[#777d78]">Calculando patrimônio...</div>}</section><footer className="mt-8 border-t border-white/[.05] pt-6 text-[10px] text-[#555b56]"><p className={storageError ? "text-rose-400" : ""}>{storageError ? "Não foi possível acessar o armazenamento deste navegador." : "Vestra · Dados salvos somente neste navegador."}</p></footer></div>;
}
