import { calculateBehaviorMetrics } from "./behaviorMetrics.js";
import { createDiagnostic, createScore } from "./diagnosticTypes.js";

export function analyzeBehavior(operations, generatedAt, rules) {
  const metrics = calculateBehaviorMetrics(operations, generatedAt, rules.behaviorNearbyOperationDays), diagnostics = [], enough = metrics.historyMonths >= rules.behaviorMinimumHistoryMonths && metrics.validOperationCount >= rules.behaviorMinimumOperations;
  if (enough) {
    diagnostics.push(item("behavior-contribution-frequency", "Frequência mensal de aportes", `Foram registrados aportes em ${metrics.activeContributionMonths} dos últimos seis meses.`, { activeMonths: metrics.activeContributionMonths, observedMonths: 6 }, "info"));
    diagnostics.push(item("behavior-contribution-regularity", "Constância dos aportes", `A frequência observada de meses com aportes foi de ${format(metrics.monthlyContributionFrequency * 100)}% no período.`, { frequencyPercent: metrics.monthlyContributionFrequency * 100 }, metrics.monthlyContributionFrequency < 0.5 ? "medium" : "info"));
    if (metrics.topTwoContributionPercent >= rules.behaviorContributionConcentrationPercent) diagnostics.push(item("behavior-asset-concentration", "Concentração dos aportes por ativo", `${format(metrics.topTwoContributionPercent)}% dos aportes dos últimos registros foram direcionados a dois ativos.`, { topTwoPercent: metrics.topTwoContributionPercent, byAsset: metrics.contributionsByAsset }, "medium"));
    if (metrics.topClassContributionPercent >= rules.behaviorContributionConcentrationPercent) diagnostics.push(item("behavior-class-concentration", "Concentração dos aportes por classe", `${format(metrics.topClassContributionPercent)}% dos aportes foram registrados em uma única classe.`, { topClassPercent: metrics.topClassContributionPercent, byClass: metrics.contributionsByClass }, "medium"));
    if (Math.abs(metrics.rhythmChangePercent) >= rules.behaviorRelevantRhythmDifferencePercent) diagnostics.push(item("behavior-rhythm-change", "Mudança recente no ritmo de aportes", `O volume aportado nos últimos três meses ficou ${format(Math.abs(metrics.rhythmChangePercent))}% ${metrics.rhythmChangePercent < 0 ? "abaixo" : "acima"} dos três meses anteriores.`, { changePercent: metrics.rhythmChangePercent, recentValue: metrics.recentContributionValue, previousValue: metrics.previousContributionValue }, "medium"));
    if (metrics.nearbyOperations > 0) diagnostics.push(item("behavior-nearby-operations", "Operações em intervalo curto", `${metrics.nearbyOperations} operações ocorreram com intervalo de até ${rules.behaviorNearbyOperationDays} dias em relação ao registro anterior.`, { count: metrics.nearbyOperations, intervalDays: rules.behaviorNearbyOperationDays }, "low"));
    if (metrics.incomeCount >= rules.behaviorMinimumOperations) diagnostics.push(item("behavior-income-recurrence", "Recorrência de proventos", `Foram registrados proventos em ${metrics.incomeMonths} meses distintos.`, { incomeMonths: metrics.incomeMonths, incomeOperations: metrics.incomeCount }, "info"));
    if (metrics.incomeCount >= rules.behaviorMinimumOperations && metrics.topIncomePercent >= rules.maxIncomeSourcePercent) diagnostics.push(item("behavior-income-dependency", "Concentração da renda registrada", `${format(metrics.topIncomePercent)}% dos proventos registrados vieram de um único ativo.`, { topIncomePercent: metrics.topIncomePercent, byAsset: metrics.incomeByAsset }, "medium"));
  }
  if (metrics.closedPositions.length >= rules.behaviorMinimumClosedPositions) { const short = metrics.closedPositions.filter((entry) => entry.holdingDays < rules.behaviorShortHoldingDays); diagnostics.push(item("behavior-average-holding", "Tempo médio entre compra e encerramento", `O tempo médio observado nas posições encerradas foi de ${format(metrics.averageHoldingDays)} dias.`, { averageHoldingDays: metrics.averageHoldingDays, closedPositions: metrics.closedPositions.length }, "info")); if (short.length) diagnostics.push(item("behavior-short-holdings", "Posições encerradas em intervalo curto", `${short.length} posições encerradas permaneceram registradas por menos de ${rules.behaviorShortHoldingDays} dias.`, { count: short.length, positions: short }, "medium")); }
  if (metrics.saleCount >= rules.behaviorMinimumSalesForTurnover && enough) diagnostics.push(item("behavior-turnover", "Giro da carteira", `O valor de saídas registrado equivale a ${format(metrics.turnoverPercent)}% do volume de aportes observado.`, { turnoverPercent: metrics.turnoverPercent, sales: metrics.saleCount }, metrics.turnoverPercent > 100 ? "medium" : "info"));
  const weights = rules.scoreWeights.behaviorConsistency, regularity = metrics.monthlyContributionFrequency * 100, stability = enough ? Math.max(0, 100 - Math.min(100, Math.abs(metrics.rhythmChangePercent))) : 0, dispersion = metrics.totalContributions > 0 ? Math.max(0, 100 - metrics.topTwoContributionPercent) : 0, sufficiency = Math.min(100, Math.min(metrics.historyMonths / rules.behaviorMinimumHistoryMonths, metrics.validOperationCount / rules.behaviorMinimumOperations) * 100), score = createScore(regularity * weights.regularity + stability * weights.rhythmStability + dispersion * weights.assetDispersion + sufficiency * weights.historySufficiency, enough ? 1 : sufficiency / 100, enough ? [] : ["Histórico insuficiente para avaliar todos os componentes."]);
  return { diagnostics, score, metrics, sufficientHistory: enough };
}
function item(id, title, summary, metrics, severity) { return { ...createDiagnostic({ id, category: "behavior", severity, status: severity === "info" ? "observed" : "attention", title, summary, evidence: [metrics], metrics, confidence: 1, limitations: ["O diagnóstico descreve registros históricos e não infere intenção."] }), scope: "behavior" }; }
function format(value) { return Number(Number(value).toFixed(1)).toLocaleString("pt-BR", { maximumFractionDigits: 1 }); }
