import { createDiagnostic } from "./diagnosticTypes.js";

export const RISK_PROFILE_PARAMETERS = Object.freeze({ conservative: Object.freeze({ suggestedMaxPositionPercent: 10, suggestedMaxClassPercent: 40, suggestedVariableIncomePercent: 30, suggestedCryptoPercent: 0, suggestedCashReservePercent: 20 }), moderate: Object.freeze({ suggestedMaxPositionPercent: 15, suggestedMaxClassPercent: 55, suggestedVariableIncomePercent: 55, suggestedCryptoPercent: 5, suggestedCashReservePercent: 10 }), aggressive: Object.freeze({ suggestedMaxPositionPercent: 25, suggestedMaxClassPercent: 70, suggestedVariableIncomePercent: 80, suggestedCryptoPercent: 10, suggestedCashReservePercent: 5 }) });

export function assessRiskProfile(answers = {}, calculatedAt = null) {
  const required = ["experienceLevel", "investmentHorizonYears", "liquidityNeed", "incomeStability", "lossTolerancePercent", "emergencyReserveStatus", "primaryObjective"];
  const missing = required.filter((field) => answers[field] === "" || answers[field] === null || answers[field] === undefined);
  if (missing.length) return { calculatedProfile: null, score: null, parameters: null, rules: scoringRules(), confidence: 0, limitations: ["Responda todas as perguntas para calcular o perfil."], missing };
  if (!Number.isFinite(Number(answers.investmentHorizonYears)) || Number(answers.investmentHorizonYears) < 0 || Number(answers.investmentHorizonYears) > 100) throw new Error("INVALID_HORIZON");
  if (!Number.isFinite(Number(answers.lossTolerancePercent)) || Number(answers.lossTolerancePercent) < 0 || Number(answers.lossTolerancePercent) > 100) throw new Error("INVALID_LOSS_TOLERANCE");
  const points = { experience: ({ beginner: 0, intermediate: 1, advanced: 2 })[answers.experienceLevel], horizon: Number(answers.investmentHorizonYears) < 3 ? 0 : Number(answers.investmentHorizonYears) < 8 ? 1 : 2, liquidity: ({ high: 0, medium: 1, low: 2 })[answers.liquidityNeed], income: ({ low: 0, medium: 1, high: 2 })[answers.incomeStability], loss: Number(answers.lossTolerancePercent) <= 10 ? 0 : Number(answers.lossTolerancePercent) <= 25 ? 1 : 2, reserve: ({ none: 0, partial: 1, complete: 2 })[answers.emergencyReserveStatus], objective: ({ preserve_capital: 0, income: 0.5, balanced_growth: 1, long_term_growth: 2 })[answers.primaryObjective] };
  if (Object.values(points).some((value) => !Number.isFinite(value))) throw new Error("INVALID_ANSWERS");
  const score = Object.values(points).reduce((sum, value) => sum + value, 0), calculatedProfile = score <= 5 ? "conservative" : score <= 10 ? "moderate" : "aggressive";
  return { calculatedProfile, score, parameters: RISK_PROFILE_PARAMETERS[calculatedProfile], rules: scoringRules(), points, answers: { ...answers }, confidence: 1, limitations: ["O perfil descreve respostas declaradas e não mede risco de mercado."], calculatedAt };
}

export function riskParametersToStrategy(parameters) { const variable = parameters.suggestedVariableIncomePercent, crypto = Math.min(parameters.suggestedCryptoPercent, variable), growth = variable - crypto, cash = parameters.suggestedCashReservePercent, defensive = 100 - variable - cash; return { maxPositionPercent: parameters.suggestedMaxPositionPercent, maxClassPercent: parameters.suggestedMaxClassPercent, targetAllocation: { "Ações": round(growth * 0.5), ETFs: round(growth * 0.3), BDRs: round(growth * 0.2), Cripto: round(crypto), FIIs: round(defensive * 0.3), "Renda Fixa": round(defensive * 0.7), Caixa: round(cash), Outros: 0 } }; }

export function analyzeRiskProfileCoherence({ positions = [], totalValue = 0, riskProfile }) { if (!riskProfile?.calculatedProfile) return []; const params = RISK_PROFILE_PARAMETERS[riskProfile.calculatedProfile], allocation = classAllocation(positions, totalValue), variable = sum(allocation, ["Ações", "ETFs", "BDRs", "FIIs", "Cripto"]), crypto = allocation.Cripto || 0, liquid = (allocation.Caixa || 0) + (allocation["Renda Fixa"] || 0), volatile = sum(allocation, ["Ações", "ETFs", "BDRs", "Cripto"]), list = []; if (variable > params.suggestedVariableIncomePercent) list.push(coherence("risk-profile-variable-income", "Renda variável e perfil", `Seu perfil calculado é ${profileLabel(riskProfile.calculatedProfile)}. A carteira possui ${format(variable)}% em renda variável.`, { currentPercent: variable, referencePercent: params.suggestedVariableIncomePercent })); if (crypto > params.suggestedCryptoPercent) list.push(coherence("risk-profile-crypto", "Exposição em cripto", `Seu perfil calculado é ${profileLabel(riskProfile.calculatedProfile)}. A exposição identificada em cripto é de ${format(crypto)}%.`, { currentPercent: crypto, referencePercent: params.suggestedCryptoPercent })); if (riskProfile.liquidityNeed === "high" && liquid < params.suggestedCashReservePercent) list.push(coherence("risk-profile-liquidity", "Liquidez declarada", `Você informou alta necessidade de liquidez. A exposição identificada em caixa e renda fixa é de ${format(liquid)}%.`, { currentPercent: liquid, referencePercent: params.suggestedCashReservePercent })); if (riskProfile.emergencyReserveStatus === "none") list.push(coherence("risk-profile-emergency-reserve", "Reserva de emergência", "Você informou não possuir reserva de emergência completa ou parcial.", { status: "none" })); if (Number(riskProfile.investmentHorizonYears) < 3 && volatile > params.suggestedVariableIncomePercent) list.push(coherence("risk-profile-short-horizon", "Horizonte e ativos voláteis", `Você informou horizonte inferior a três anos. A exposição identificada em classes voláteis é de ${format(volatile)}%.`, { horizonYears: riskProfile.investmentHorizonYears, currentPercent: volatile })); return list; }

function coherence(id, title, summary, metrics) { return { ...createDiagnostic({ id, category: "risk", severity: "medium", status: "attention", title, summary, evidence: [metrics], metrics, confidence: 1, limitations: ["A comparação usa classes identificadas e referências derivadas do questionário."] }), scope: "risk_profile" }; }
function classAllocation(positions, total) { return positions.reduce((map, item) => { const key = normalizedClass(item.type); map[key] = (map[key] || 0) + (total > 0 ? Number(item.currentValue || 0) / total * 100 : 0); return map; }, {}); }
function normalizedClass(value = "") { const text = value.toLocaleLowerCase("pt-BR"); if (text.includes("fii") || text.includes("fundo imobili")) return "FIIs"; if (text.includes("etf")) return "ETFs"; if (text.includes("bdr")) return "BDRs"; if (text.includes("cripto")) return "Cripto"; if (text.includes("renda fixa") || text.includes("tesouro") || text.includes("cdb")) return "Renda Fixa"; if (text.includes("caixa")) return "Caixa"; if (text.includes("ação") || text.includes("acao") || text.includes("unit")) return "Ações"; return "Outros"; }
function scoringRules() { return { dimensions: 7, pointsPerDimension: "0 a 2", conservative: "até 5", moderate: "acima de 5 até 10", aggressive: "acima de 10" }; }
function sum(map, keys) { return keys.reduce((total, key) => total + (map[key] || 0), 0); }
function round(value) { return Math.round(value * 100) / 100; }
function format(value) { return Number(Number(value).toFixed(1)).toLocaleString("pt-BR", { maximumFractionDigits: 1 }); }
function profileLabel(value) { return ({ conservative: "conservador", moderate: "moderado", aggressive: "agressivo" })[value]; }
