import { createDiagnostic } from "./diagnosticTypes.js";

export function analyzeStrategy({ positions, totalValue, parameters, rules }) {
  if (!hasStrategy(parameters)) return [];
  const diagnostics = [], byClass = allocationByClass(positions, totalValue);
  const byAsset = positions.filter((item) => Number(item.currentValue) > 0).map((item) => ({ ticker: item.ticker, percent: totalValue > 0 ? Number(item.currentValue) / totalValue * 100 : 0 })).sort((a, b) => b.percent - a.percent);
  if (parameters.maxPositionPercent !== null && parameters.maxPositionPercent !== undefined) byAsset.filter((item) => item.percent > parameters.maxPositionPercent).forEach((item) => diagnostics.push(strategyDiagnostic({ id: `strategy-position-${item.ticker}`, category: "concentration", severity: "high", title: "Limite por ativo", summary: `Você definiu limite de ${format(parameters.maxPositionPercent)}% por ativo. ${item.ticker} representa atualmente ${format(item.percent)}%.`, evidence: [item], metrics: { configuredLimitPercent: parameters.maxPositionPercent, currentPercent: item.percent, differencePercent: item.percent - parameters.maxPositionPercent } })));
  if (parameters.maxClassPercent !== null && parameters.maxClassPercent !== undefined) byClass.filter((item) => item.percent > parameters.maxClassPercent).forEach((item) => diagnostics.push(strategyDiagnostic({ id: `strategy-class-${slug(item.key)}`, category: "concentration", severity: "high", title: "Limite por classe", summary: `Você definiu limite de ${format(parameters.maxClassPercent)}% por classe. ${item.key} representa atualmente ${format(item.percent)}%.`, evidence: [item], metrics: { configuredLimitPercent: parameters.maxClassPercent, currentPercent: item.percent, differencePercent: item.percent - parameters.maxClassPercent } })));
  for (const [assetClass, target] of Object.entries(parameters.targetAllocation || {})) {
    const current = byClass.find((item) => item.key === assetClass)?.percent || 0, difference = current - Number(target);
    diagnostics.push(strategyDiagnostic({ id: `strategy-target-${slug(assetClass)}`, category: "allocation", severity: Math.abs(difference) > rules.targetAllocationTolerancePercent ? "medium" : "info", status: Math.abs(difference) > rules.targetAllocationTolerancePercent ? "attention" : "observed", title: `Alocação-alvo de ${assetClass}`, summary: `Sua meta para ${assetClass} é ${format(target)}%. A alocação atual é ${format(current)}%.`, evidence: [{ assetClass, targetPercent: Number(target), currentPercent: current }], metrics: { targetPercent: Number(target), currentPercent: current, differencePercent: difference } }));
  }
  diagnostics.push(...missingPreferred(parameters.preferredCountries, positions, "country", "país", "country"));
  diagnostics.push(...missingPreferred(parameters.preferredCurrencies, positions, "currency", "moeda", "currency"));
  const focus = focusDiagnostic(parameters.investmentFocus, byClass, rules);
  if (focus) diagnostics.push(focus);
  return diagnostics;
}

function strategyDiagnostic(input) { return { ...createDiagnostic({ status: "attention", confidence: 1, limitations: [], ...input }), scope: "strategy" }; }
function allocationByClass(positions, totalValue) { const map = positions.reduce((result, item) => { if (Number(item.currentValue) > 0) { const key = normalizedClass(item.type); result[key] = (result[key] || 0) + Number(item.currentValue); } return result; }, {}); return Object.entries(map).map(([key, value]) => ({ key, value, percent: totalValue > 0 ? value / totalValue * 100 : 0 })).sort((a, b) => b.value - a.value); }
function normalizedClass(value = "") { const text = value.toLocaleLowerCase("pt-BR"); if (text.includes("fii") || text.includes("fundo imobili")) return "FIIs"; if (text.includes("etf")) return "ETFs"; if (text.includes("bdr")) return "BDRs"; if (text.includes("cripto")) return "Cripto"; if (text.includes("renda fixa") || text.includes("tesouro") || text.includes("cdb")) return "Renda Fixa"; if (text.includes("caixa")) return "Caixa"; if (text.includes("ação") || text.includes("acao") || text.includes("unit")) return "Ações"; return "Outros"; }
function missingPreferred(preferred, positions, field, label, idPart) { const known = new Set(positions.map((item) => String(item[field] || "").toLocaleLowerCase("pt-BR")).filter(Boolean)); return (preferred || []).filter((item) => !known.has(String(item).toLocaleLowerCase("pt-BR"))).map((item) => strategyDiagnostic({ id: `strategy-${idPart}-${slug(item)}`, category: "diversification", severity: "medium", title: `${label[0].toUpperCase()}${label.slice(1)} preferido sem exposição`, summary: `${item} foi definido como ${label} preferido, mas não há exposição identificada nessa referência.`, evidence: [{ preferred: item, identifiedExposure: false }], metrics: { preferred: item, identifiedExposure: false }, confidence: positions.some((position) => position[field]) ? 1 : 0.3, limitations: positions.some((position) => position[field]) ? [] : [`Dados de ${label} estão incompletos.`] })); }
function focusDiagnostic(focus, byClass, rules) { if (!focus || focus === "custom" || !byClass.length) return null; const map = Object.fromEntries(byClass.map((item) => [item.key, item.percent])); const incomePercent = (map.FIIs || 0) + (map["Renda Fixa"] || 0), growthPercent = (map["Ações"] || 0) + (map.ETFs || 0) + (map.BDRs || 0) + (map.Cripto || 0); let conflict = false, observed = 0, expected = 0; if (focus === "income") { observed = incomePercent; expected = rules.incomeFocusMinimumPercent; conflict = observed < expected; } if (focus === "growth") { observed = growthPercent; expected = rules.growthFocusMinimumPercent; conflict = observed < expected; } if (focus === "balanced") { observed = Math.max(...byClass.map((item) => item.percent)); expected = rules.balancedFocusMaximumClassPercent; conflict = observed > expected; } if (!conflict) return null; const labels = { income: "renda", growth: "crescimento", balanced: "equilibrado" }; return strategyDiagnostic({ id: `strategy-focus-${focus}`, category: "allocation", severity: "medium", title: "Composição e foco definido", summary: `Você definiu foco ${labels[focus]}. A composição atual não atende à referência transparente configurada para esse foco.`, evidence: byClass, metrics: { focus, observedPercent: observed, referencePercent: expected }, limitations: ["O foco usa apenas classes identificadas e não avalia características individuais dos ativos."] }); }
function hasStrategy(value = {}) { return value.maxPositionPercent !== null && value.maxPositionPercent !== undefined || value.maxClassPercent !== null && value.maxClassPercent !== undefined || Object.keys(value.targetAllocation || {}).length > 0 || (value.preferredCountries || []).length > 0 || (value.preferredCurrencies || []).length > 0 || Boolean(value.riskProfile) || Boolean(value.investmentFocus); }
function format(value) { return Number(Number(value).toFixed(1)).toLocaleString("pt-BR", { maximumFractionDigits: 1 }); }
function slug(value) { return String(value).normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-zA-Z0-9]+/g, "-").toLowerCase(); }
