"use client";
import { useMemo, useState } from "react";
import { CalendarClock, Check, Link2, RefreshCw, Undo2 } from "lucide-react";
import useAutomaticIncome from "@/hooks/useAutomaticIncome";
import { currency } from "@/lib/engine/totals";

const labels = { DIVIDEND: "Dividendo", JCP: "JCP", INCOME: "Rendimento", EXPECTED: "Esperado", ELIGIBLE: "Elegível", IGNORED: "Ignorado", CANCELLED: "Cancelado", CONFLICT: "Revisar", RECONCILED: "Conciliado" };
export default function AutomaticIncomePanel({ data }) {
  const automatic = useAutomaticIncome(data.dataSource); const [confirming, setConfirming] = useState(null);
  const visible = useMemo(() => automatic.expectations.filter((item) => item.status !== "RECONCILED"), [automatic.expectations]);
  const next30 = useMemo(() => { const limit = new Date(Date.now() + 30 * 86400000).toISOString().slice(0, 10); return visible.filter((item) => item.expectedPaymentDate && item.expectedPaymentDate <= limit && !["IGNORED", "CANCELLED", "CONFLICT"].includes(item.status)).reduce((sum, item) => sum + Number(item.expectedNetAmount ?? item.grossAmount), 0); }, [visible]);
  if (data.dataSource?.source !== "SUPABASE") return <section className="card mt-6 rounded-2xl p-6"><h2 className="font-display text-2xl">A receber</h2><p className="mt-3 text-sm text-[#898e89]">As expectativas automáticas ficam disponíveis quando a fonte ativa é Supabase. Seus proventos recebidos continuam intactos.</p></section>;
  return <>
    <section className="mt-6 grid gap-3 sm:grid-cols-2"><article className="card rounded-2xl p-5"><p className="eyebrow">Próximos 30 dias</p><p className="mt-3 text-2xl font-semibold">{currency.format(next30)}</p></article><article className="card rounded-2xl p-5"><p className="eyebrow">Expectativas abertas</p><p className="mt-3 text-2xl font-semibold">{visible.filter((item) => item.status !== "IGNORED").length}</p></article></section>
    <section className="card mt-6 rounded-2xl p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-display text-2xl">A receber</h2><p className="mt-1 text-xs text-[#777d78]">Descobertas automáticas que só viram recebimento após sua confirmação.</p></div>{data.dataSource?.canWrite && <button className="gold-button flex items-center justify-center gap-2" disabled={automatic.loading} onClick={automatic.sync}><RefreshCw size={16} className={automatic.loading ? "animate-spin" : ""} />Atualizar proventos</button>}</div>{automatic.error && <p role="alert" className="mt-4 text-sm text-rose-300">{automatic.error}</p>}{automatic.summary && <p className="mt-4 text-xs text-[#898e89]">{automatic.summary.expectationsCreated} nova(s) expectativa(s); nenhuma operação criada automaticamente.</p>}</section>
    <section className="mt-4 space-y-3">{automatic.loading && !visible.length ? <Empty text="Carregando expectativas..." /> : !visible.length ? <Empty text="Nenhum provento esperado foi encontrado." /> : visible.map((item) => <article key={item.id} className="card rounded-2xl p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><strong>{item.ticker}</strong><span className="rounded-full border border-white/10 px-2 py-1 text-[10px] uppercase">{labels[item.eventType]}</span><span className="text-xs text-[#d9b86c]">{labels[item.status] || item.status}</span></div><p className="mt-2 text-sm text-[#898e89]">{item.assetName || item.ticker} · pagamento {item.expectedPaymentDate || "a confirmar"}</p><div className="mt-3 grid gap-1 text-xs text-[#777d78] sm:grid-cols-2"><span>Quantidade elegível: {item.eligibleQuantity}</span><span>Valor por unidade: {currency.format(item.grossAmountPerUnit)}</span><span>Data de corte: {item.eligibilityDate}</span><span>Fonte: {item.source} · confiança {item.confidence}</span></div></div><div className="shrink-0 sm:text-right"><p className="text-xl font-semibold text-[#d9b86c]">{currency.format(item.expectedNetAmount ?? item.grossAmount)}</p><p className="mt-1 text-xs text-[#777d78]">{item.expectedNetAmount == null ? "Bruto; líquido a confirmar" : "Líquido esperado"}</p></div></div>{data.dataSource?.canWrite && <div className="mt-5 flex flex-wrap gap-2">{item.status === "IGNORED" ? <button className="icon-button flex w-auto gap-2 px-3" onClick={() => automatic.restore(item.id)}><Undo2 size={14} />Restaurar</button> : <><button className="gold-button flex items-center gap-2" disabled={["CANCELLED", "CONFLICT"].includes(item.status)} onClick={() => setConfirming(item)}><Check size={14} />Confirmar recebimento</button>{item.matchStatus === "EXACT_MATCH" && item.matchCandidateOperationId && <button className="icon-button flex w-auto gap-2 px-3" onClick={() => automatic.link(item.id, item.matchCandidateOperationId)}><Link2 size={14} />Vincular existente</button>}<button className="icon-button flex w-auto gap-2 px-3" onClick={() => automatic.ignore(item.id, "Ignorado pelo usuário")} >Ignorar</button></>}</div>}</article>)}</section>
    {confirming && <ConfirmModal item={confirming} onClose={() => setConfirming(null)} onConfirm={async (date, amount) => { await automatic.confirm(confirming.id, date, amount); setConfirming(null); }} />}
  </>;
}
function ConfirmModal({ item, onClose, onConfirm }) { const [date, setDate] = useState(item.expectedPaymentDate || new Date().toISOString().slice(0, 10)); const [amount, setAmount] = useState(item.expectedNetAmount ?? item.grossAmount); return <div className="fixed inset-0 z-[80] grid place-items-center bg-black/75 p-4"><div role="dialog" aria-modal="true" aria-labelledby="confirm-income-title" className="card w-full max-w-lg rounded-2xl p-6"><h2 id="confirm-income-title" className="font-display text-2xl">Confirmar recebimento</h2><p className="mt-2 text-sm text-[#898e89]">Revise a data e o valor efetivamente recebido. A confirmação cria uma operação real.</p><label className="form-label mt-5 block">Data efetiva<input className="field mt-2" type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><label className="form-label mt-4 block">Valor recebido<input className="field mt-2" type="number" min="0.01" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><div className="mt-6 flex justify-end gap-2"><button onClick={onClose}>Cancelar</button><button className="gold-button" onClick={() => onConfirm(date, amount)}>Confirmar</button></div></div></div>; }
function Empty({ text }) { return <div className="card rounded-2xl px-6 py-14 text-center"><CalendarClock className="mx-auto text-[#d9b86c]" /><p className="mt-4 text-sm text-[#777d78]">{text}</p></div>; }
