import { analyzeAssetContributions } from "./contributionAnalysis.js";
import { calculateMaximumDrawdown } from "./drawdownAnalysis.js";
import { buildPerformanceTimeline, contributionRegularity } from "./timelineAnalysis.js";
import { calculateWealthGrowth } from "./wealthGrowth.js";
import { PERFORMANCE_LIMITS, clamp, performanceScore } from "./performanceTypes.js";

export function generatePerformanceAnalysis(input = {}) { const history = normalizeHistory(input.history), operations = Array.isArray(input.operations) ? input.operations : [], positions = Array.isArray(input.positions) ? input.positions : [], growth = calculateWealthGrowth(history, operations), drawdown = calculateMaximumDrawdown(history), contributions = analyzeAssetContributions(positions), timeline = buildPerformanceTimeline(history), historyPoints = history.length, activeMonths = historyPoints ? contributionRegularity(operations, history[0].date, history.at(-1).date) : 0, growthRate = growth.startWealth > 0 ? growth.growth / growth.startWealth * 100 : growth.growth > 0 ? 100 : 0, growthComponent = clamp(50 + growthRate), regularityComponent = clamp(activeMonths / PERFORMANCE_LIMITS.fullRegularityMonths * 100), stabilityComponent = clamp(100 - drawdown.percent * 2), sufficiencyComponent = clamp(historyPoints / PERFORMANCE_LIMITS.fullConfidencePoints * 100), scoreValue = growthComponent * 0.3 + regularityComponent * 0.3 + stabilityComponent * 0.25 + sufficiencyComponent * 0.15, sufficientHistory = historyPoints >= PERFORMANCE_LIMITS.minimumHistoryPoints, limitations = [!sufficientHistory && "São necessários ao menos dois registros históricos.", "Contribuições de ativos encerrados podem não aparecer no ranking atual.", "A valorização é o componente residual após fluxos líquidos e proventos."].filter(Boolean); return { generatedAt: input.generatedAt || null, summary: sufficientHistory ? `O patrimônio acompanhado variou ${formatCurrency(growth.growth)} no período observado.` : "Histórico insuficiente para calcular a evolução patrimonial.", growth, drawdown, contributions, timeline, scores: { wealth_consistency: performanceScore(scoreValue, Math.min(1, historyPoints / PERFORMANCE_LIMITS.fullConfidencePoints), limitations) }, dataQuality: { historyPoints, activeContributionMonths: activeMonths, sufficientHistory }, limitations }; }
function normalizeHistory(value) { if (!Array.isArray(value)) return []; const map = new Map(); value.filter((item) => item && /^\d{4}-\d{2}-\d{2}$/.test(item.date || "")).forEach((item) => map.set(item.date, item)); return [...map.values()].sort((a, b) => a.date.localeCompare(b.date)); }
function formatCurrency(value) { return Number(value).toLocaleString("pt-BR", { style: "currency", currency: "BRL" }); }
