"use client";

import { useState } from "react";
import { Edit3, RefreshCw } from "lucide-react";
import QuoteModal from "@/components/quotes/QuoteModal";
import DataManagement from "@/components/settings/DataManagement";
import useInvestmentData from "@/hooks/useInvestmentData";
import { currency } from "@/lib/engine/totals";

export default function QuotesSettings() {
  const { positions, assetsMaster, setAssetsMaster, assetQuotes, setAssetQuotes, loaded, storageError } = useInvestmentData();
  const [editing, setEditing] = useState(null);
  const save = (quote) => { const { sector, notes, ...dynamicQuote } = quote; setAssetQuotes((current) => [...current.filter((item) => item.ticker !== quote.ticker), dynamicQuote]); setAssetsMaster((current) => current.map((asset) => asset.ticker === quote.ticker ? { ...asset, sector, notes } : asset)); setEditing(null); };
  return <div className="page-container"><header><p className="eyebrow">Preferências</p><h1 className="font-display mt-2 text-3xl sm:text-4xl">Configurações</h1><p className="mt-3 max-w-2xl text-sm text-[#777d78]">Gerencie cotações, backups e os dados locais da aplicação.</p></header><section className="card mt-8 overflow-hidden rounded-2xl"><div className="border-b border-white/[.06] p-5 sm:p-6"><h2 className="font-display text-xl">Dados e cotações</h2><p className="mt-1 text-xs text-[#777d78]">Atualização manual, sem conexão com APIs externas.</p></div>{!loaded ? <div className="p-12 text-center text-sm text-[#777d78]">Carregando ativos...</div> : positions.length === 0 ? <div className="px-5 py-12 text-center"><RefreshCw size={21} className="mx-auto text-[#d9b86c]" /><h3 className="font-display mt-4 text-xl">Nenhum ativo para atualizar</h3></div> : <div className="divide-y divide-white/[.05]">{positions.map((position) => { const quote = assetQuotes.find((item) => item.ticker === position.ticker), master = assetsMaster.find((item) => item.ticker === position.ticker); return <div key={position.ticker} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">{position.ticker}</p><p className="mt-1 text-xs text-[#777d78]">{position.name}{master?.sector ? ` · ${master.sector}` : ""}</p></div><div className="flex items-center justify-between gap-5"><div className="text-right"><p className="text-sm font-semibold">{quote ? currency.format(quote.currentQuote) : "Não informada"}</p><p className="mt-1 text-[9px] text-[#626762]">{quote ? quote.updatedAt.split("-").reverse().join("/") : "Usando preço médio"}</p></div><button onClick={() => setEditing(position)} aria-label={`Atualizar cotação ${position.ticker}`} className="icon-button"><Edit3 size={15} /></button></div></div>; })}</div>}</section><DataManagement />{storageError && <p className="mt-4 text-xs text-rose-400">Não foi possível salvar os dados neste navegador.</p>}{editing && <QuoteModal detailed assetsMaster={assetsMaster} position={editing} masterAsset={assetsMaster.find((item) => item.ticker === editing.ticker)} quote={assetQuotes.find((item) => item.ticker === editing.ticker)} onClose={() => setEditing(null)} onSave={save} />}</div>;
}
