import { getSupabaseRepositoryClient, throwSupabaseRepositoryError } from "./supabaseRepositoryUtils.js";

const SELECT = `id, portfolio_id, event_id, eligible_quantity, gross_amount, known_withholding_amount, expected_net_amount, currency, eligibility_date, expected_payment_date, status, confidence, match_status, match_candidate_operation_id, ignored_at, ignored_reason, confirmed_at, reconciled_at, corporate_income_events (ticker, asset_name, event_type, status, record_date, ex_date, gross_amount_per_unit, source, version)`;
function fromRow(row) { const event = row.corporate_income_events || {}; return { id: row.id, portfolioId: row.portfolio_id, eventId: row.event_id, eligibleQuantity: Number(row.eligible_quantity), grossAmount: Number(row.gross_amount), knownWithholdingAmount: row.known_withholding_amount == null ? null : Number(row.known_withholding_amount), expectedNetAmount: row.expected_net_amount == null ? null : Number(row.expected_net_amount), currency: row.currency, eligibilityDate: row.eligibility_date, expectedPaymentDate: row.expected_payment_date, status: row.status, confidence: row.confidence, matchStatus: row.match_status, matchCandidateOperationId: row.match_candidate_operation_id, ignoredAt: row.ignored_at, ignoredReason: row.ignored_reason, confirmedAt: row.confirmed_at, reconciledAt: row.reconciled_at, ticker: event.ticker, assetName: event.asset_name, eventType: event.event_type, eventStatus: event.status, recordDate: event.record_date, exDate: event.ex_date, grossAmountPerUnit: Number(event.gross_amount_per_unit), source: event.source, eventVersion: event.version }; }
export function createSupabaseIncomeExpectationsRepository(client) {
  const db = () => getSupabaseRepositoryClient(client);
  return {
    async listByPortfolio(portfolioId) { const { data, error } = await db().from("portfolio_income_expectations").select(SELECT).eq("portfolio_id", portfolioId).order("expected_payment_date", { ascending: true }); throwSupabaseRepositoryError(error); return (data || []).map(fromRow); },
    async ignore(id, reason = "") { const { error } = await db().from("portfolio_income_expectations").update({ status: "IGNORED", ignored_at: new Date().toISOString(), ignored_reason: reason || null }).eq("id", id); throwSupabaseRepositoryError(error, "write"); },
    async restore(id) { const { error } = await db().from("portfolio_income_expectations").update({ status: "EXPECTED", ignored_at: null, ignored_reason: null }).eq("id", id).eq("status", "IGNORED"); throwSupabaseRepositoryError(error, "write"); },
    async confirm(id, effectiveDate, amount, notes = "") { const { data, error } = await db().rpc("confirm_income_expectation", { target_expectation_id: id, effective_date: effectiveDate, received_amount: amount, operation_notes: notes }); throwSupabaseRepositoryError(error, "write"); return data; },
    async link(id, operationId) { const { data, error } = await db().rpc("link_income_expectation", { target_expectation_id: id, target_operation_id: operationId }); throwSupabaseRepositoryError(error, "write"); return data; },
  };
}
export const supabaseIncomeExpectationsRepository = createSupabaseIncomeExpectationsRepository();
